version: 1.0.{build}-{branch}
branches:
  only:
    - master
environment:
  matrix:
    #- nodejs_version: "0.12"
    - nodejs_version: "0.11"
    - nodejs_version: "0.10"
    - nodejs_version: "1"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off