var fs = require('fs')
  , path = require('path')
  , root = process.cwd().replace(/node_modules\//, '')
  , utils = require('./utils')
  , hooks = require('./hooks')
  , userHooksDir = '.hooks';

var gh = {

  root: root,

  userHooks: userHooksDir,

  isGitProject: function() {
    return utils.dirExists(path.join(root, '.git'));
  },

  hasGitHooksDir: function() {
    return utils.dirExists(path.join(root, '.git/hooks'));
  },

  hasUserHooksDir: function() {
    return utils.dirExists(path.join(root, userHooksDir));
  },

  setupHooks: function() {
    var userHooks = fs.readdirSync(path.join(root, userHooksDir)) || [];

    hooks.forEach(function(hook) {
      var userHook = path.join(root, userHooksDir, hook);
      if(utils.fileExists(userHook)) {
        var targetPath = path.join(root, '.git/hooks', hook);

        // check to see if the user already has a git hook
        if(utils.fileExists(targetPath) &&
          !fs.readFileSync(targetPath, 'UTF-8').match('Generated by git-hooked. Do not modify!')) {
          console.log(
            'Found an existing hook for ' + hook + '\n' +
            'Backing up to .git/hooks/' + hook + '.user'
          );
          fs.renameSync(targetPath, targetPath + '.user');
        }

        console.log('Installing ' + hook + ' hook...')

        fs.createReadStream(path.join(__dirname, 'hook.template.js'))
          .pipe(fs.createWriteStream(targetPath, hook))
        fs.chmod(targetPath, 0755);
        fs.chmod(userHook, 0755);
      }

    });

  }

};

module.exports = gh;