module.exports = [
  'applypatch-msg',
  'pre-applypatch',
  'post-applypatch',
  'post-commit',
  'pre-commit',
  'commit-msg',
  'prepare-commit-msg',
  'pre-rebase',
  'post-checkout',
  'post-merge',
  'pre-push',
  'pre-receive',
  'update',
  'post-receive',
  'post-update',
  'pre-auto-gc',
  'post-rewrite'
];